# Generated by Django 5.2.11 on 2026-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplace',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projectplace',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
