# Generated by Django 5.2.11 on 2026-02-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_project', '0002_projectplace_artist_projectplace_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectplace',
            table='project_place',
        ),
        migrations.AlterModelTable(
            name='travelproject',
            table='travel_project',
        ),
    ]
